/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Recipe } from "./types";
export { Recipe } from "./types";
export namespace Components {
    /**
     * Placeholder shown when a list has nothing in it.
     */
    interface RfEmptyState {
        /**
          * Emoji or short glyph shown above the message.
          * @default '🍳'
         */
        "icon": string;
        /**
          * The headline message.
          * @default 'Nothing here yet'
         */
        "message": string;
    }
    /**
     * One assignable cell of the weekly meal planner, e.g. Monday / Dinner.
     * Renders the assigned recipe when there is one, and falls back to whatever the
     * host puts in the default slot when empty — so the app controls the empty-state
     * copy and the "assign" affordance without the library hard-coding either.
     */
    interface RfMealSlot {
        /**
          * Day this slot belongs to, e.g. "Monday".
         */
        "day": string;
        /**
          * The assigned recipe, or null when the slot is free. A JSON attribute also works.
          * @default null
         */
        "meal": Partial<Recipe> | string | null;
        /**
          * Meal name, e.g. "Dinner". Named `slotName` because `slot` is reserved.
         */
        "slotName": string;
    }
    /**
     * A minimal modal dialog whose entire content comes from slots.
     * The host owns the `open` state; the component only asks to be closed.
     */
    interface RfModal {
        /**
          * Dialog heading text.
          * @default ''
         */
        "heading": string;
        /**
          * Whether the dialog is visible. Reflected so CSS can hide the host.
          * @default false
         */
        "open": boolean;
    }
    /**
     * A recipe summary card.
     * Receives the whole recipe as an object property (not a set of string
     * attributes) and emits custom events upward; the host application owns all
     * favourite/navigation state.
     */
    interface RfRecipeCard {
        /**
          * Whether this recipe is currently in the user's favourites.
          * @default false
         */
        "favorite": boolean;
        /**
          * The recipe to display. Pass as a property; a JSON attribute also works.
         */
        "recipe": Recipe | string;
    }
    /**
     * Search input plus category/area filter selects.
     * Fully controlled from the host: the app passes the current query and the
     * available filter options in as properties, and reacts to the emitted events.
     * The component holds only transient input state.
     */
    interface RfSearchBar {
        /**
          * Currently selected area, or '' for all.
          * @default ''
         */
        "area": string;
        /**
          * Selectable areas/cuisines. Accepts an array, or a comma-separated attribute.
          * @default []
         */
        "areas": string[] | string;
        /**
          * Selectable categories. Accepts an array, or a comma-separated attribute.
          * @default []
         */
        "categories": string[] | string;
        /**
          * Currently selected category, or '' for all.
          * @default ''
         */
        "category": string;
        /**
          * Current search term.
          * @default ''
         */
        "value": string;
    }
}
export interface RfMealSlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfMealSlotElement;
}
export interface RfModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfModalElement;
}
export interface RfRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfRecipeCardElement;
}
export interface RfSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfSearchBarElement;
}
declare global {
    /**
     * Placeholder shown when a list has nothing in it.
     */
    interface HTMLRfEmptyStateElement extends Components.RfEmptyState, HTMLStencilElement {
    }
    var HTMLRfEmptyStateElement: {
        prototype: HTMLRfEmptyStateElement;
        new (): HTMLRfEmptyStateElement;
    };
    interface HTMLRfMealSlotElementEventMap {
        "rfAssign": {
    day: string;
    slot: string;
    replacing: boolean;
  };
        "rfRemove": { day: string; slot: string };
        "rfOpen": { id: string };
    }
    /**
     * One assignable cell of the weekly meal planner, e.g. Monday / Dinner.
     * Renders the assigned recipe when there is one, and falls back to whatever the
     * host puts in the default slot when empty — so the app controls the empty-state
     * copy and the "assign" affordance without the library hard-coding either.
     */
    interface HTMLRfMealSlotElement extends Components.RfMealSlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfMealSlotElementEventMap>(type: K, listener: (this: HTMLRfMealSlotElement, ev: RfMealSlotCustomEvent<HTMLRfMealSlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfMealSlotElementEventMap>(type: K, listener: (this: HTMLRfMealSlotElement, ev: RfMealSlotCustomEvent<HTMLRfMealSlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfMealSlotElement: {
        prototype: HTMLRfMealSlotElement;
        new (): HTMLRfMealSlotElement;
    };
    interface HTMLRfModalElementEventMap {
        "rfClose": void;
    }
    /**
     * A minimal modal dialog whose entire content comes from slots.
     * The host owns the `open` state; the component only asks to be closed.
     */
    interface HTMLRfModalElement extends Components.RfModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfModalElementEventMap>(type: K, listener: (this: HTMLRfModalElement, ev: RfModalCustomEvent<HTMLRfModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfModalElementEventMap>(type: K, listener: (this: HTMLRfModalElement, ev: RfModalCustomEvent<HTMLRfModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfModalElement: {
        prototype: HTMLRfModalElement;
        new (): HTMLRfModalElement;
    };
    interface HTMLRfRecipeCardElementEventMap {
        "rfFavoriteToggle": {
    id: string;
    favorite: boolean;
  };
        "rfOpen": { id: string };
    }
    /**
     * A recipe summary card.
     * Receives the whole recipe as an object property (not a set of string
     * attributes) and emits custom events upward; the host application owns all
     * favourite/navigation state.
     */
    interface HTMLRfRecipeCardElement extends Components.RfRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfRecipeCardElementEventMap>(type: K, listener: (this: HTMLRfRecipeCardElement, ev: RfRecipeCardCustomEvent<HTMLRfRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfRecipeCardElementEventMap>(type: K, listener: (this: HTMLRfRecipeCardElement, ev: RfRecipeCardCustomEvent<HTMLRfRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfRecipeCardElement: {
        prototype: HTMLRfRecipeCardElement;
        new (): HTMLRfRecipeCardElement;
    };
    interface HTMLRfSearchBarElementEventMap {
        "rfSearch": { q: string };
        "rfFilterChange": {
    category: string;
    area: string;
  };
    }
    /**
     * Search input plus category/area filter selects.
     * Fully controlled from the host: the app passes the current query and the
     * available filter options in as properties, and reacts to the emitted events.
     * The component holds only transient input state.
     */
    interface HTMLRfSearchBarElement extends Components.RfSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfSearchBarElementEventMap>(type: K, listener: (this: HTMLRfSearchBarElement, ev: RfSearchBarCustomEvent<HTMLRfSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfSearchBarElementEventMap>(type: K, listener: (this: HTMLRfSearchBarElement, ev: RfSearchBarCustomEvent<HTMLRfSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfSearchBarElement: {
        prototype: HTMLRfSearchBarElement;
        new (): HTMLRfSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "rf-empty-state": HTMLRfEmptyStateElement;
        "rf-meal-slot": HTMLRfMealSlotElement;
        "rf-modal": HTMLRfModalElement;
        "rf-recipe-card": HTMLRfRecipeCardElement;
        "rf-search-bar": HTMLRfSearchBarElement;
    }
}
declare namespace LocalJSX {
    /**
     * Placeholder shown when a list has nothing in it.
     */
    interface RfEmptyState {
        /**
          * Emoji or short glyph shown above the message.
          * @default '🍳'
         */
        "icon"?: string;
        /**
          * The headline message.
          * @default 'Nothing here yet'
         */
        "message"?: string;
    }
    /**
     * One assignable cell of the weekly meal planner, e.g. Monday / Dinner.
     * Renders the assigned recipe when there is one, and falls back to whatever the
     * host puts in the default slot when empty — so the app controls the empty-state
     * copy and the "assign" affordance without the library hard-coding either.
     */
    interface RfMealSlot {
        /**
          * Day this slot belongs to, e.g. "Monday".
         */
        "day"?: string;
        /**
          * The assigned recipe, or null when the slot is free. A JSON attribute also works.
          * @default null
         */
        "meal"?: Partial<Recipe> | string | null;
        /**
          * Emitted when the user wants to choose a recipe for this slot — both when filling an empty slot and when swapping the one already in it. `replacing` distinguishes the two so the host can adjust its wording.
         */
        "onRfAssign"?: (event: RfMealSlotCustomEvent<{
    day: string;
    slot: string;
    replacing: boolean;
  }>) => void;
        /**
          * Emitted when the user opens the assigned recipe.
         */
        "onRfOpen"?: (event: RfMealSlotCustomEvent<{ id: string }>) => void;
        /**
          * Emitted when the user clears this slot.
         */
        "onRfRemove"?: (event: RfMealSlotCustomEvent<{ day: string; slot: string }>) => void;
        /**
          * Meal name, e.g. "Dinner". Named `slotName` because `slot` is reserved.
         */
        "slotName"?: string;
    }
    /**
     * A minimal modal dialog whose entire content comes from slots.
     * The host owns the `open` state; the component only asks to be closed.
     */
    interface RfModal {
        /**
          * Dialog heading text.
          * @default ''
         */
        "heading"?: string;
        /**
          * Emitted when the user dismisses the dialog.
         */
        "onRfClose"?: (event: RfModalCustomEvent<void>) => void;
        /**
          * Whether the dialog is visible. Reflected so CSS can hide the host.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * A recipe summary card.
     * Receives the whole recipe as an object property (not a set of string
     * attributes) and emits custom events upward; the host application owns all
     * favourite/navigation state.
     */
    interface RfRecipeCard {
        /**
          * Whether this recipe is currently in the user's favourites.
          * @default false
         */
        "favorite"?: boolean;
        /**
          * Emitted when the favourite button is pressed.
         */
        "onRfFavoriteToggle"?: (event: RfRecipeCardCustomEvent<{
    id: string;
    favorite: boolean;
  }>) => void;
        /**
          * Emitted when the user asks to open the full recipe.
         */
        "onRfOpen"?: (event: RfRecipeCardCustomEvent<{ id: string }>) => void;
        /**
          * The recipe to display. Pass as a property; a JSON attribute also works.
         */
        "recipe"?: Recipe | string;
    }
    /**
     * Search input plus category/area filter selects.
     * Fully controlled from the host: the app passes the current query and the
     * available filter options in as properties, and reacts to the emitted events.
     * The component holds only transient input state.
     */
    interface RfSearchBar {
        /**
          * Currently selected area, or '' for all.
          * @default ''
         */
        "area"?: string;
        /**
          * Selectable areas/cuisines. Accepts an array, or a comma-separated attribute.
          * @default []
         */
        "areas"?: string[] | string;
        /**
          * Selectable categories. Accepts an array, or a comma-separated attribute.
          * @default []
         */
        "categories"?: string[] | string;
        /**
          * Currently selected category, or '' for all.
          * @default ''
         */
        "category"?: string;
        /**
          * Emitted when either filter select changes.
         */
        "onRfFilterChange"?: (event: RfSearchBarCustomEvent<{
    category: string;
    area: string;
  }>) => void;
        /**
          * Emitted when the user submits a search.
         */
        "onRfSearch"?: (event: RfSearchBarCustomEvent<{ q: string }>) => void;
        /**
          * Current search term.
          * @default ''
         */
        "value"?: string;
    }

    interface RfEmptyStateAttributes {
        "icon": string;
        "message": string;
    }
    interface RfMealSlotAttributes {
        "day": string;
        "slotName": string;
        "meal": Partial<Recipe> | string | null;
    }
    interface RfModalAttributes {
        "open": boolean;
        "heading": string;
    }
    interface RfRecipeCardAttributes {
        "recipe": Recipe | string;
        "favorite": boolean;
    }
    interface RfSearchBarAttributes {
        "value": string;
        "categories": string[] | string;
        "areas": string[] | string;
        "category": string;
        "area": string;
    }

    interface IntrinsicElements {
        "rf-empty-state": Omit<RfEmptyState, keyof RfEmptyStateAttributes> & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes]?: RfEmptyState[K] } & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes as `attr:${K}`]?: RfEmptyStateAttributes[K] } & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes as `prop:${K}`]?: RfEmptyState[K] };
        "rf-meal-slot": Omit<RfMealSlot, keyof RfMealSlotAttributes> & { [K in keyof RfMealSlot & keyof RfMealSlotAttributes]?: RfMealSlot[K] } & { [K in keyof RfMealSlot & keyof RfMealSlotAttributes as `attr:${K}`]?: RfMealSlotAttributes[K] } & { [K in keyof RfMealSlot & keyof RfMealSlotAttributes as `prop:${K}`]?: RfMealSlot[K] };
        "rf-modal": Omit<RfModal, keyof RfModalAttributes> & { [K in keyof RfModal & keyof RfModalAttributes]?: RfModal[K] } & { [K in keyof RfModal & keyof RfModalAttributes as `attr:${K}`]?: RfModalAttributes[K] } & { [K in keyof RfModal & keyof RfModalAttributes as `prop:${K}`]?: RfModal[K] };
        "rf-recipe-card": Omit<RfRecipeCard, keyof RfRecipeCardAttributes> & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes]?: RfRecipeCard[K] } & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes as `attr:${K}`]?: RfRecipeCardAttributes[K] } & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes as `prop:${K}`]?: RfRecipeCard[K] };
        "rf-search-bar": Omit<RfSearchBar, keyof RfSearchBarAttributes> & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes]?: RfSearchBar[K] } & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes as `attr:${K}`]?: RfSearchBarAttributes[K] } & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes as `prop:${K}`]?: RfSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Placeholder shown when a list has nothing in it.
             */
            "rf-empty-state": LocalJSX.IntrinsicElements["rf-empty-state"] & JSXBase.HTMLAttributes<HTMLRfEmptyStateElement>;
            /**
             * One assignable cell of the weekly meal planner, e.g. Monday / Dinner.
             * Renders the assigned recipe when there is one, and falls back to whatever the
             * host puts in the default slot when empty — so the app controls the empty-state
             * copy and the "assign" affordance without the library hard-coding either.
             */
            "rf-meal-slot": LocalJSX.IntrinsicElements["rf-meal-slot"] & JSXBase.HTMLAttributes<HTMLRfMealSlotElement>;
            /**
             * A minimal modal dialog whose entire content comes from slots.
             * The host owns the `open` state; the component only asks to be closed.
             */
            "rf-modal": LocalJSX.IntrinsicElements["rf-modal"] & JSXBase.HTMLAttributes<HTMLRfModalElement>;
            /**
             * A recipe summary card.
             * Receives the whole recipe as an object property (not a set of string
             * attributes) and emits custom events upward; the host application owns all
             * favourite/navigation state.
             */
            "rf-recipe-card": LocalJSX.IntrinsicElements["rf-recipe-card"] & JSXBase.HTMLAttributes<HTMLRfRecipeCardElement>;
            /**
             * Search input plus category/area filter selects.
             * Fully controlled from the host: the app passes the current query and the
             * available filter options in as properties, and reacts to the emitted events.
             * The component holds only transient input state.
             */
            "rf-search-bar": LocalJSX.IntrinsicElements["rf-search-bar"] & JSXBase.HTMLAttributes<HTMLRfSearchBarElement>;
        }
    }
}
